from enum import IntEnum


class Length(IntEnum):

    MAX_LEN_RECIPES_CHARFIELD = 200
    MAX_LEN_MEASUREMENT_UNIT = 200
    MIN_COOKING_TIME = 1
    MAX_COOKING_TIME = 1440
    MIN_AMOUNT_OF_INGREDIENTS = 1
    MAX_AMOUNT_OF_INGREDIENTS = 256
    MAX_LENGTH_EMAIL = 254
    MAX_LENGTH_USERNAME = 150
    MAX_LENGTH_CONFIRMATION_CODE = 150
    MAX_LENGTH_FIRST_NAME = 150
    MAX_LENGTH_LAST_NAME = 150
    MAX_LENGTH_ROLE = 150
    MAX_LENGTH_PASSWORD = 150
    MAX_LENGHT_COLOR_FIELD = 7
