version: '3'

services:

  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data/
    restart: always

  backend:
    image: piqadolf/foodgram_backend:latest
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db
    restart: always

  frontend:
    image: piqadolf/foodgram_frontend:latest
    env_file: .env
    volumes:
      - static:/frontend_static
    command: cp -r /app/build/. /frontend_static/
    depends_on:
      - db
    restart: always

  nginx:
    image: piqadolf/foodgram_nginx:latest
    env_file: .env
    ports:
      - 7000:80
    volumes:
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static:/static/
      - media:/app/media/
    depends_on:
      - backend
      - frontend
    restart: always

volumes:
  pg_data:
  static:
  media:
